apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-blog
  labels:
    app: technical-blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: technical-blog
  template:
    metadata:
      labels:
        app: technical-blog
    spec:
      containers:
      - name: technical-blog
        image: registry.digitalocean.com/your-registry/technical-blog:latest
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: NEXT_PUBLIC_BASE_URL
          value: "https://yourdomain.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: technical-blog-service
spec:
  type: LoadBalancer
  selector:
    app: technical-blog
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: technical-blog-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: technical-blog